name: Branch action

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment Name
        required: true
        default: dev7

jobs:
  branch:
    runs-on: ubuntu-20.04

    if: if [[ 'dev7' =~ ^dev([1-9]|10)$|integration|regression|staging ]]; then echo true; else echo false; fi
    

    steps:
      - uses: actions/checkout@v2

      - name: Get git hash
        id: hash
        run: echo "::set-output name=hash::$(git rev-parse --short=7 ${{ github.sha }})"

      - name: Get branch name
        id: branch
        run: echo "::set-output name=branch::$(BRANCH=${{ github.ref }}; BRANCH=${BRANCH#refs/heads/}; echo ${BRANCH////-})"

      - name: Log
        run: echo "${{ github.event.inputs.environment }}-${{ steps.hash.outputs.hash }}-${{ steps.branch.outputs.branch }}"
