name: Deploy branch to ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment Name
        required: true
        default: dev7

jobs:
  branch:
    runs-on: ubuntu-20.04

    if: contains(fromJson('["dev1", "dev2", "dev3", "dev4", "dev5", "dev6", "dev7", "dev8", "dev9", "dev10", "integration", "regression", "staging"]'), github.event.inputs.environment)

    steps:
      - uses: actions/checkout@v2

      - name: Get git hash
        id: hash
        run: echo "::set-output name=hash::$(git rev-parse --short=7 ${{ github.sha }})"

      - name: Get branch name
        id: branch
        run: echo "::set-output name=branch::$(BRANCH=${{ github.ref }}; BRANCH=${BRANCH#refs/heads/}; echo ${BRANCH////-})"

      - name: Log
        run: echo "${{ github.event.inputs.environment }}-${{ steps.hash.outputs.hash }}-${{ steps.branch.outputs.branch }}"
