name: test

on:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1

      - name: Get git tag
        id: tag
        run: echo "::set-output name=tag::$(git --no-pager describe --tags $(git rev-list --tags --max-count=1))"

      - name: Update package version
        run: |
          npm --no-git-tag-version --allow-same-version version ${{ steps.tag.outputs.tag }}
          git push
