name: test

on:
  release:
    types: [published]
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1

      - name: Get git hash
        id: hash
        run: echo ::set-output name=hash::$(git rev-parse --short=7 ${{ github.sha }})

      - name: Get git tag
        id: tag
        run: echo "::set-output name=tag::$(git --no-pager describe --tags $(git rev-list --tags --max-count=1))"

      - name: Update package version
        run: |
          git config user.name GitHub Actions
          git config user.email action@github.com
          npm version ${{ steps.tag.outputs.tag }} --no-git-tag-version --allow-same-version
          git commit -am "${{ steps.tag.outputs.tag }}"
          git push origin HEAD:master

  foo:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get git hash
        id: hash
        run: echo ::set-output name=hash::$(git rev-parse --short=7 ${{ github.sha }})

      - name: Get git tag
        id: tag
        run: echo "::set-output name=tag::$(git --no-pager describe --tags $(git rev-list --tags --max-count=1))"
      
      - name: echo stuff
        run: |
          echo ${{ steps.hash.outputs.hash }}
          echo ${{ steps.tag.outputs.tag }}
