name: test

on:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Use Node.js 12
        uses: actions/setup-node@v1

      - name: Get git hash
        id: hash
        run: echo "::set-output name=hash::$(git rev-parse --short=7 ${{ github.sha }})"

      - name: Update package version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version ${{ github.ref }} --no-git-tag-version --allow-same-version
          git push
