name: test2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment Name
        required: true
        default: dev7
  push:
    branches:
      - feature/test2

jobs:
  test2:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get git hash
        id: hash
        run: echo "::set-output name=hash::$(git rev-parse --short=7 ${{ github.sha }})"

      - name: Get branch name
        id: branch
        run: echo "::set-output name=branch::$(BRANCH=${{ github.ref }}; BRANCH=${BRANCH#refs/heads/}; echo ${BRANCH////-})"

      - name: Log
        run: echo "${{ github.event.inputs.environment | 'dev7' }}-${{ steps.hash.outputs.hash }}-${{ steps.branch.outputs.branch }}"
